name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Extract keystore file
      run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > $GITHUB_WORKSPACE/signing-key.jks

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      
    - name: Build Release APK
      run: |
        ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/signing-key.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PW }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.KEYSTORE_ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.KEYSTORE_PW }}
    
    - run: rm $GITHUB_WORKSPACE/signing-key.jks
    
    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: APK(s) debug generated
        path: ./app/build/outputs/apk/debug/
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: APK(s) release generated
        path: ./app/build/outputs/apk/release/
